name: C/C++ CI

on: push

jobs:

  build:
  
    runs-on: windows-latest

    steps:
    
      - uses: actions/checkout@v2
      - name: install valgrind and cpplint
      
        run: |
          sudo apt install valgrind
          sudo pip install cpplint
      - name: compiling and test
        
        run: |
           make
